config/routes.rb
ELMS::Application.routes.draw do
 

  devise_for :employees
  resources :employees
 
  resources :leave_applications do 
    get :profile,on: :collection
    get :show_status, on: :collection
    get :archive, on: :collection
    get :report, on: :collection
    get :reportDept, on: :collection
    get :reportEmp, on: :collection
    get :management, on: :collection
    put :updateReview, on: :member
    put :submitApp, on: :member
    get :pdfGen, on: :collection
    get :pdfGenDept, on: :collection
    get :pdfGenEmp, on: :collection
    post :showDetails, on: :collection
  end

   resources :deletions
   resources :roles

   devise_scope :employee do
    root to: "devise/sessions#new"
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
 
  devise :database_authenticatable,:recoverable, :rememberable, :trackable, :validatable

 
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :phone, :role_id,:department_id,:leave_balance, :leave_bal
  

  validates :name, :phone, :role_id,:department_id, presence: true

  belongs_to :role
  belongs_to :department
  has_many :leave_applications, :dependent => :destroy
 
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

 helper_method :sort_column,:sort_direction

  def index

    if current_employee.role_id == 4 || current_employee.role_id == 5
      @search = Employee.search(params[:q])
      @employees = @search.result(:distinct => true).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 5)
    else
      flash[:alert] = "You are not allowed to access this page!"
      redirect_to leave_applications_path
    end

      
    
  end

  def destroy
    @employees = Employee.find(params[:id])
    @employees.destroy 

    flash[:notice] = "User has been deleted"
    redirect_to employees_path
  end

  def show
    @show = Employee.find(params[:id])
  end

  def new
    if current_employee.role_id == 4 || current_employee.role_id == 5
      @departments = Department.all
      @roles = Role.all
      @employees = Employee.new
    else
      flash[:alert] = "You are not allowed to access this page!"
      redirect_to leave_applications_path
    end
  end

  def create
    @employees = Employee.new(params[:employee])
    @curr_emp = Employee.find(current_employee)
    if @employees.save
      flash[:notice] = "Successfully created User!"
      sign_in @curr_emp, :bypass => true
      redirect_to employees_path
    else
      flash[:alert] = "Error creating the User!"
      render 'new'
    end
  end

  def edit
    @employees = Employee.find(params[:id])
  end

  def update
    @employees = Employee.find(params[:id])

  if @employees.update_attributes(params[:employee])
      flash[:notice] = "Successfully updated User details!"
      sign_in @employees, :bypass => true
      redirect_to employee_path(params[:id])
    else
      flash[:alert] = "Error creating updating the User details!"
      render 'edit'
    end
  end
def sort_column
    Employee.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employees.html.erb
<table class="pretty">
<tr>
<th>No</th>
<th><%=sortable "name" %></th>
<th>Department</th>
<th>Role</th>
<th>Actions</th>
</tr>

<% @employees.each_with_index do |f,i| %>
<tr>
	<td><%= i+1  %></td>
	<td><%= f.name %></td>
	<td><%= Department.where(id:f.department_id).pluck("department_name").join("") %></td>
	<td><%= Role.where(id:f.role_id).pluck("role_name").join("") %></td>
	<td><%= link_to 'Details',employee_path(f.id)%></td>
</tr>
<% end %>
</table>
<%= will_paginate @pages %> 

app/views/employees/_form.html.erb
<center>
<% if @employees.errors.any? %>
	<div id="formError">
		<h2>Errors :</h2>
		<ul>
			<% @employees.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
</center>
<center>
<div id="reportFilter2">
	<fieldset>
		<legend><b>Form</b></legend>
	<%= form_for @employees,:html => { :id => "reg_employee" } do |f| %>
	 
	<div><b><%= f.label :name %></b><br />
	<%= f.text_field :name %></div><br>
	 
	<div><b><%= f.label :password %></b><br/>
	<%= f.password_field :password %></div><br>
	 
	<div><b><%= f.label :password_confirmation %></b><br />
	<%= f.password_field :password_confirmation %></div><br>

	<% if current_employee.role_id == 4 || current_employee.role_id == 5 %>
	<div><b><%= f.label :department %></b><br />
		<%= f.select :department_id, [["Software",1],["Network",2],["Sales",3],["Marketing",4]],
			{prompt: "Select Department"}%></div><br>

	<div><b><%= f.label :role %></b><br />
	<%= f.select :role_id, [["Staff",1],["Manager",2],["Management",3],["Administrator",4],["Manager/Administrator",5]],
			{prompt: "Select Role"}%></div><br>
	<% end %>

	<div><b><%= f.label :phone %></b><br />
	<%= f.text_field :phone %></div><br>

	<div><b><%= f.label :email %></b><br />
	<%= f.email_field :email, :autofocus => true %></div><br>

	<div><%= f.submit "Submit" %></div>

	<% end %>
	</fieldset>
</div>
</center>

app/views/employees/edit.html.erb
<h1>Edit Profile</h1>
<%= render 'form' %>
<br/>
<%= button_to "Back" , :back,method: :get%>

app/views/employees/index.html.erb
<center>
<h2>List of Employees</h2>

<p><%= search_form_for @search do |f| %>
	
  <%= f.label :role_id_eq, "Role :" %>
  <%= f.select :role_id_eq, options_for_select([["Please Select",nil],["Staff",1],["Manager",2],["Management",3],["Administrator",4],["Manager/Administrator",5]]) %>
	
  <%= f.label :department_id_eq, "Department :" %>
  <%= f.select :department_id_eq, options_for_select([["Please Select",nil],["Software",1],["Network",2],["Sales",3],["Marketing",4]]) %>
  
  <%= f.submit "Search" %></p>
<% end %>


<div id="employees"><%= render 'employees' %></div>
</center>



<br>
<%= button_to 'Add User' , new_employee_path, method: :get %>

app/views/employees/index.js.erb
$('div#employees').html('<%= j render("employees") %>');

app/views/employees/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>
<br/>
<%= link_to "Back" , :back %>

app/views/employees/show.html.erb
<h1>Employees</h1>
<br>

<center>
<table>
<tr>
<th>Name: </th>
<td><%= @show.name %></td>
</tr>

<tr>
<th>ID: </th>
<td><%= @show.id %></td>
</tr>

<tr>
<th>Role: </th>
<td><%= Role.where(id:@show.role_id).pluck("role_name").join("") %></td>
</tr>

<tr>
<th>Department: </th>
<td><%= Department.where(id:@show.department_id).pluck("department_name").join("")  %></td>
</tr>

<tr>
<th>Phone no: </th>
<td><%= @show.phone %></td>
</tr>

<tr>
<th>E-mail: </th>
<td><%= @show.email %></td>
</tr>

</table>
</center>
<br><br>

<% if current_employee == @show %>
		<center><%= button_to "Edit Profile", edit_employee_path(@show),method: :get%></center>
<% elsif current_employee.role_id == 4 || current_employee.role_id == 5 %>
<center>
<%= button_to "Edit Employee", edit_employee_path(@show),method: :get%>
<%= button_to "Remove User", @employees , :method => :delete , :confirm => "Are you sure ?"%>
</center>
<% end %>