config/routes.rb
ELMS::Application.routes.draw do
 

  devise_for :employees
  resources :employees
 
  resources :leave_applications do 
    get :profile,on: :collection
    get :show_status, on: :collection
    get :archive, on: :collection
    get :report, on: :collection
    get :reportDept, on: :collection
    get :reportEmp, on: :collection
    get :management, on: :collection
    put :updateReview, on: :member
    put :submitApp, on: :member
    get :pdfGen, on: :collection
    get :pdfGenDept, on: :collection
    get :pdfGenEmp, on: :collection
    post :showDetails, on: :collection
  end

   resources :deletions
   resources :roles

   devise_scope :employee do
    root to: "devise/sessions#new"
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :role_name

  has_many :employees
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

	def index
		if current_employee.role_id == 4 || current_employee.role_id == 5
			@roles = Role.all
		end
	end

	def new
		if current_employee.role_id == 4 || current_employee.role_id == 5
			@role = Role.new
		end
	end

	def create 

	end

	def edit 

	end

	def update

	end

end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for @role do |f|%>
<center>
<div id="reportFilter2">
<fieldset>
	<legend><b>New Application</b></legend>
<% if @role.errors.any? %>
	<div id="formError">
		<h2>Errors :</h2>
		<ul>
			<% @role.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div>
	<%= f.label :role_name %>:<br/>
	<%= f.text_field :role_name %>
</div>
 <%= f.submit 'Submit'%>
</fieldset>
</div>
</center>
<% end %>

app/views/roles/_roles.html.erb
<center>
<table>
	<tr>
		<th>No</th>
		<th>Role Name</th>
		<th>Action</th>
	</tr>
		<% @roles.each_with_index do |r,i| %>
			<tr>
				<td><%= i+1 %></td>
				<td><%= r.role_name %></td>
				<td><%= link_to 'Edit Role', edit_role_path(r.id)%></td>
			</tr>
		<% end %>
</table>
</center>

app/views/roles/index.html.erb
<h1>List Of Roles</h1>

<%= render "roles" %>

<%= link_to 'Create New Role', new_role_path,remote:true%>

app/views/roles/new.html.erb
<h1>Add New Role</h1>
<%= render 'form' %>

app/views/roles/show.html.erb
<h1>Role Details</h1>

<center>
	<table>
		<tr>
			<td></td>
			<td></td>
		</tr>	
		<tr>
			<td></td>
			<td></td>
		</tr>	
		<tr>
			<td></td>
			<td></td>
		</tr>	
	</table>
</center>