config/routes.rb
ELMS::Application.routes.draw do
 

  devise_for :employees
  resources :employees
 
  resources :leave_applications do 
    get :profile,on: :collection
    get :show_status, on: :collection
    get :archive, on: :collection
    get :report, on: :collection
    get :reportDept, on: :collection
    get :reportEmp, on: :collection
    get :management, on: :collection
    put :updateReview, on: :member
    put :submitApp, on: :member
    get :pdfGen, on: :collection
    get :pdfGenDept, on: :collection
    get :pdfGenEmp, on: :collection
    post :showDetails, on: :collection
  end

   resources :deletions
   resources :roles

   devise_scope :employee do
    root to: "devise/sessions#new"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= favicon_link_tag 'logo.jpg'%>
  <title>Employee Leave Management System</title>
  <%= stylesheet_link_tag    "application"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<div class="myModalContainer">
</div>
<body>
	
	<div id='wrapper'>
				<div id='header'>
					<%= image_tag("logo.jpg", :alt => "rss feed", :id=>"img") %>
					<h1>Employee Leave Management System</h1>
						<% if employee_signed_in? %>
					
						<ul id='nav'>
							<li><%= link_to 'Home',leave_applications_path %></li>
							<li>
								<a href="#">Leave Application</a>
								<ul class="nav">
									<li><%= link_to 'Application Status', show_status_leave_applications_path %></li>
									<li><%= link_to 'Application Archive', archive_leave_applications_path %></li>
										<% if current_employee.role_id == 2 || current_employee.role_id == 3 || current_employee.role_id == 5 %>
											<li>
												<a href='#'>Report</a>
												<ul class="nav2">
													<li><%= link_to 'Total Leave Application',report_leave_applications_path %></li>
													<li><%= link_to 'Leave Application by Departments',reportDept_leave_applications_path %></li>
													<li><%= link_to 'Leave Application by Employees',reportEmp_leave_applications_path  %></li>
												</ul>
											</li>
											<li><%= link_to 'Application Management',management_leave_applications_path %></li>
											<li><%= link_to 'Removed Application Notifications',deletions_path %></li>
										<% end %>
								</ul>

							<li>
								<a href="#">Profile Management</a>
								<ul class="nav">
									<li><%= link_to 'View Profile',employee_path(current_employee)%></li>
										<% if current_employee.role_id == 4 || current_employee.role_id == 5 %>
											<li><%= link_to 'User Management' , employees_path %></li>
										<% end %>
								</ul>
							</li>

							<li>Leave balance : <span id="lb"><%= current_employee.leave_balance %></span></li>
							<li><%= link_to 'Logout', destroy_employee_session_path, method: :delete %></li>
						</ul>
					<% end %>
					<div class='clearfix'></div>
				</div>
			
			<div id='content'>
					<% flash.each do |key,msg|%>
						<%= content_tag :div, msg, id:key %>
					<% end %>
				<p>
				
					<%= yield %>
				</p>
			</div>
			<div id='footer'>
				<p>
					&copy Internship Sri Komputer 2013
				</p>
			</div>
		</div>
	</body>
</html>